import type { Metadata } from "next"
// import { GeistMono } from "geist-font"
// import { GeistSans } from "geist-font"

export const metadata: Metadata = {
  title: "rajanavadhane.dev",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
